// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

 static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyCWu3rm-lsDeQE4NEoYlF4PdyUeAlVjDew",
  authDomain: "curadomusapp.firebaseapp.com",
  projectId: "curadomusapp",
  storageBucket: "curadomusapp.firebasestorage.app",
  messagingSenderId: "765026817343",
  appId: "1:765026817343:web:bc4e3264a2e1ce4e7bef8a",
  measurementId: "G-VECCB6CR8P",
);


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2wsPl5pHg3QGJn9l0WrmltPLmdWlufg',
    appId: '1:765026817343:android:099912fc7374985e7bef8a',
    messagingSenderId: '765026817343',
    projectId: 'curadomusapp',
    storageBucket: 'curadomusapp.appspot.com', // ✅ FIXED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcDFdIV2T4mGJQFMtfKfKvIyA2TaVDgbg',
    appId: '1:765026817343:ios:6f800b6a1a5f02767bef8a',
    messagingSenderId: '765026817343',
    projectId: 'curadomusapp',
    storageBucket: 'curadomusapp.appspot.com', // ✅ FIXED
    iosBundleId: 'com.example.curadomusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcDFdIV2T4mGJQFMtfKfKvIyA2TaVDgbg',
    appId: '1:765026817343:ios:6f800b6a1a5f02767bef8a',
    messagingSenderId: '765026817343',
    projectId: 'curadomusapp',
    storageBucket: 'curadomusapp.appspot.com', // ✅ FIXED
    iosBundleId: 'com.example.curadomusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCWu3rm-lsDeQE4NEoYlF4PdyUeAlVjDew",
    appId: "1:765026817343:web:bc4e3264a2e1ce4e7bef8a",
    messagingSenderId: "765026817343",
    projectId: "curadomusapp",
    authDomain: "curadomusapp.firebaseapp.com",
    storageBucket: "curadomusapp.appspot.com", // ✅ FIXED
    measurementId: "G-VECCB6CR8P",
  );
}
